---
- include_tasks:        "../../tasks/remove_packages.yml"
- include_tasks:        "../../tasks/commands.yml"
- include_tasks:        "../../tasks/disable_services.yml"
  when:                 "commands_result.stdout is defined and 'systemd-resolved' in commands_result.stdout"
- include_tasks:        "../../tasks/stop_services.yml"
  when:                 "commands_result.stdout is defined and 'systemd-resolved' in commands_result.stdout"
- include_tasks:        "../../tasks/template_files.yml"
