---
- shell:                                test -e /lib/systemd/systemd-resolved
  failed_when:                          False
  changed_when:                         False
  register:                             presence_result

- include_tasks:                        '../tasks/disable_services.yml'
  when:                                 0 == presence_result.rc

- include_tasks:                        '../tasks/stop_services.yml'
  when:                                 0 == presence_result.rc
